### ISSUE TITLE
fwiw

### ISSUE THREAD

**Issue by jonschlinkert** [jonschlinkert/arrayify-compact#1]
@es128 thanks for pointing out arrify, just went ahead and deleted that project since I forgot I had this one. fwiw:
- Jul 6, 2014: https://github.com/jonschlinkert/arrayify-compact/commit/466fdfdc6c3bbdc78a89a2d95f6e21665b2ce4a5#diff-168726dbe96b3ce427e7fedce31bb0bcR13
- Feb 16, 2015: https://github.com/sindresorhus/arrify/commit/da49fca6ec001bc8d450fbe0262db599ad345006#diff-168726dbe96b3ce427e7fedce31bb0bcR7

arrify is different enough that it serves a different purpose and makes sense to exist. just pointing out this out

**Comment by es128** [comment]
Right, no worries. I only commented on that other new repo because it didn't seem like it had any notable distinction (I did take a quick look at source code of both before submitting the issue)

**Comment by jonschlinkert** [comment]
makes total sense, thx again for letting me know
